# Generated by Django 6.0.6 on 2026-07-08 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0038_proposal_moa_draft_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MOADocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='moa_uploads/%Y/%m/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft_generated', 'Draft Generated'), ('uploaded', 'Uploaded by Coordinator'), ('under_review', 'Under Review'), ('revisions_requested', 'Revisions Requested'), ('finalized', 'Finalized / Signed')], default='draft_generated', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moa_documents', to='proposals.proposal')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('proposal', 'version'), name='unique_moa_version_per_proposal')],
            },
        ),
    ]
