# Generated by Django 6.0.2 on 2026-02-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('EVALUATOR', 'Evaluators'), ('COORDINATOR', 'Coordinators'), ('DIRECTOR', 'Director'), ('ADMIN', 'Admin')], default='FACULTY', max_length=20),
        ),
    ]
