# Generated by Django 6.0.2 on 2026-03-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_created_at_profile_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('STAFF', 'Staff'), ('EVALUATOR', 'Evaluator'), ('COLLEGE_COORDINATOR', 'College Coordinator'), ('CAMPUS_COORDINATOR', 'Campus Coordinator'), ('DIRECTOR', 'Director'), ('ADMIN', 'Admin')], default='FACULTY', max_length=20),
        ),
    ]
