# Generated by Django 6.0.2 on 2026-03-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('STAFF', 'Staff'), ('EVALUATOR', 'Evaluator'), ('DEPARTMENT_COORDINATOR', 'Department Coordinator'), ('CAMPUS_COORDINATOR', 'Campus Coordinator'), ('DIRECTOR', 'Director'), ('ADMIN', 'Admin')], default='FACULTY', max_length=200),
        ),
    ]
