# Generated by Django 6.0.2 on 2026-03-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='otp',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='campus',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('STAFF', 'Staff'), ('EVALUATOR', 'Evaluator'), ('DEPARTMENT_COORDINATOR', 'Department Coordinator'), ('CAMPUS_COORDINATOR', 'Campus Coordinator'), ('DIRECTOR', 'Director'), ('ADMIN', 'Admin')], default='FACULTY', max_length=50),
        ),
    ]
