# Generated by Django 6.0.2 on 2026-03-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_emailotp_otp_alter_profile_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('STAFF', 'Staff'), ('DEPARTMENT_COORDINATOR', 'Department Coordinator'), ('CAMPUS_COORDINATOR', 'Campus Coordinator'), ('DIRECTOR', 'Director'), ('ADMIN', 'Admin')], default='FACULTY', max_length=50),
        ),
    ]
