# Generated by Django 6.0.2 on 2026-03-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='campus',
            field=models.CharField(blank=True, choices=[('Candon', 'Candon'), ('Main', 'Main'), ('Sta Maria', 'Sta Maria'), ('Cervantes', 'Cervantes'), ('Tagudin', 'Tagudin'), ('Narvacan', 'Narvacan'), ('Santiago', 'Santiago')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
