# Generated by Django 6.0.2 on 2026-04-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_campus_alter_profile_college_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('DIRECTOR_EXTENSION', 'Director for Extension'), ('CAMPUS_DIRECTOR', 'Campus Director'), ('CAMPUS_EXTENSION_COORDINATOR', 'Campus Extension Coordinator'), ('OTHER', 'Other')], default='DIRECTOR_EXTENSION', max_length=60)),
                ('campus', models.CharField(blank=True, choices=[('Candon', 'Candon'), ('Main', 'Main'), ('Sta Maria', 'Sta Maria'), ('Cervantes', 'Cervantes'), ('Tagudin', 'Tagudin'), ('Narvacan', 'Narvacan'), ('Santiago', 'Santiago')], default='', max_length=150)),
                ('full_name', models.CharField(max_length=200)),
                ('credentials', models.CharField(blank=True, default='', max_length=120)),
                ('position_title', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['purpose', 'campus', '-is_active', 'sort_order', 'full_name'],
                'constraints': [models.UniqueConstraint(fields=('purpose', 'campus', 'full_name', 'position_title', 'credentials'), name='unique_signatory_identity_per_context')],
            },
        ),
    ]
