# Generated by Django 6.0.2 on 2026-04-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_signatory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signatory',
            options={'ordering': ['position_title', 'campus', 'college', 'department', '-is_active', 'sort_order', 'full_name']},
        ),
        migrations.RemoveConstraint(
            model_name='signatory',
            name='unique_signatory_identity_per_context',
        ),
        migrations.AddField(
            model_name='signatory',
            name='college',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='signatory',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='signatory',
            name='position_title',
            field=models.CharField(choices=[('DIRECTOR_EXTENSION', 'Director for Extension'), ('DEPARTMENT_EXTENSION_COORDINATOR', 'Department Extension Coordinator'), ('DEAN', 'Dean'), ('CAMPUS_EXTENSION_COORDINATOR', 'Campus Extension Coordinator'), ('CAMPUS_DIRECTOR', 'Campus Director'), ('VPRDE', 'Vice President for Research Development and Extension'), ('SUC_PRESIDENT_III', 'SUC President III')], default='DIRECTOR_EXTENSION', max_length=80),
        ),
        migrations.AddConstraint(
            model_name='signatory',
            constraint=models.UniqueConstraint(fields=('position_title', 'campus', 'college', 'department', 'full_name', 'credentials'), name='unique_signatory_identity_per_scope'),
        ),
        migrations.RemoveField(
            model_name='signatory',
            name='purpose',
        ),
    ]
