# Generated by Django 6.0.2 on 2026-04-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_signatory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signatory',
            options={'ordering': ['position_title', 'campus', 'college', 'department', '-is_active', 'full_name']},
        ),
        migrations.RemoveField(
            model_name='signatory',
            name='sort_order',
        ),
    ]
