# Generated by Django 6.0.2 on 2026-05-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_signatory_options_remove_signatory_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signatory',
            options={'ordering': ['position_title', 'campus', 'college', 'department', 'full_name']},
        ),
        migrations.RemoveConstraint(
            model_name='signatory',
            name='unique_signatory_identity_per_scope',
        ),
        migrations.AddConstraint(
            model_name='signatory',
            constraint=models.UniqueConstraint(fields=('position_title', 'campus', 'college', 'department'), name='unique_signatory_per_position_scope'),
        ),
        migrations.RemoveField(
            model_name='signatory',
            name='is_active',
        ),
    ]
