# Generated by Django 5.2.17 on 2026-08-06

from django.db import migrations


def populate_campuses_colleges_departments(apps, schema_editor):
    Campus = apps.get_model("accounts", "Campus")
    College = apps.get_model("accounts", "College")
    Department = apps.get_model("accounts", "Department")

    CAMPUS_STRUCTURE = {
        "Candon": {
            "College of Hospitality and Tourism": [
                "Bachelor of Science in Hospitality Management",
                "Bachelor of Science in Tourism Management",
            ],
            "": [
                "Bachelor of Science in Information Technology",
                "Bachelor of Secondary Education",
            ],
        },
        "Main": {
            "College of Arts and Sciences": [
                "Bachelor of Arts in English Language",
                "Bachelor of Arts in Political Science",
                "Bachelor of Science in Computer Science",
            ],
            "College of Business Management & Entrepreneurship": [
                "Bachelor of Science in Business Administration",
                "Bachelor of Science in Office Administration",
            ],
            "Collge of Teacher Education": [
                "Bachelor of Secondary Education",
                "Bachelor of Elementary Education",
                "Bachelor of Physical Education",
                "Bachelor of Culture and Arts Education",
            ],
            "School of Criminal Justice Education": [
                "Bachelor of Science in Criminology",
            ],
            "College of Health Sciences": [
                "Bachelor of Science in Midwifery",
                "Bachelor of Science in Nursing",
            ],
        },
        "Sta Maria": {
            "College of Teacher Education (CTE)": [
                "Bachelor of Elementary Education",
                "Bachelor of Secondary Education",
                "Bachelor of Technology and Livelihood Education",
            ],
            "College of Computing Studies (CCS)": [
                "Bachelor of Science in Information Technology",
                "Bachelor of Science in Information Systems",
            ],
            "College of Agriculture, Forestry, Engineering, & Development Communication (CAFEDC)": [
                "Bachelor of Science in Agriculture",
                "Bachelor of Science in Forestry",
                "Bachelor of Science in Agroforestry",
                "Bachelor of Science in Agricultural and Biosystems Engineering",
                "Bachelor of Science in Development Communication",
            ],
            "College of Business Management and Entreprenership CBME)": [
                "Bachelor of Science in Hospitality Management",
            ],
            "College of Graduate Studies (CGS)": [
                "Doctor of Education in Educational Management",
                "Doctor of Philosophy in English Language Education",
                "Doctor of Philosophy in Agronomy",
                "Doctor of Philosophy in Technology Education Management",
                "Master of Arts in Education",
            ],
        },
        "Cervantes": {
            "": [
                "Bachelor of Elementary Education",
                "Bachelor of Secondary Education",
                "Bachelor of Science in Information Technology",
                "Bachelor of Science in Criminology",
                "Bachelor of Technology and Livelihood Education",
                "Bachelor of Technical-Vocational Teacher Education",
            ],
        },
        "Tagudin": {
            "College of Teacher Education (CTE)": [
                "Bachelor of Secondary Education",
                "Bachelor of Elementary Education",
                "Bachelor of Physical Education",
            ],
            "College of Arts and Sciences (CAS)": [
                "Bachelor of Arts in Psychology",
                "Bachelor of Arts in Social Science",
                "Bachelor of Science in Mathematics",
                "Bachelor of Science in Information Technology",
                "Bachelor of Arts in English Language",
                "Bachelor of Public Administration",
            ],
            "College of Business Management and Entrepreneurship (CBME)": [
                "Bachelor of Science in Business Administration",
                "Bachelor of Science in Entrepreneurship",
            ],
        },
        "Narvacan": {
            "": [
                "Bachelor of Science in Fisheries",
                "Bachelor of Technology and Livelihood Education",
                "Bachelor of Physical Education",
            ],
        },
        "Santiago": {
            "Institute of Technology": [
                "Bachelor of Science in Industrial Technology",
                "Bachelor of Science in Mechatronics Technology",
            ],
            "College of Teacher Education": [
                "Bachelor of Technical Vocation Teacher Education",
            ],
        },
    }

    for campus_name, colleges_dict in CAMPUS_STRUCTURE.items():
        campus_obj, _ = Campus.objects.get_or_create(name=campus_name)
        for college_name, departments_list in colleges_dict.items():
            college_obj = None
            if college_name:
                college_obj, _ = College.objects.get_or_create(
                    campus=campus_obj,
                    name=college_name
                )
            for dept_name in departments_list:
                Department.objects.get_or_create(
                    campus=campus_obj,
                    college=college_obj,
                    name=dept_name
                )


def rollback_campuses_colleges_departments(apps, schema_editor):
    Campus = apps.get_model("accounts", "Campus")
    Campus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_campus_college_department"),
    ]

    operations = [
        migrations.RunPython(
            populate_campuses_colleges_departments,
            rollback_campuses_colleges_departments
        ),
    ]
