# Generated by Django 5.2.17 on 2026-09-16 15:32

import accounts.campus_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_populate_campuses_colleges_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='campus',
            field=models.CharField(blank=True, choices=accounts.campus_data.get_campus_choices, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='signatory',
            name='campus',
            field=models.CharField(blank=True, choices=accounts.campus_data.get_campus_choices, default='', max_length=150),
        ),
    ]
