# Generated by Django 6.0.2 on 2026-03-02 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionThrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campus', models.CharField(blank=True, default='', max_length=120)),
                ('college', models.CharField(blank=True, default='', max_length=120)),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('RETURNED', 'Returned for Revision'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('extension_type', models.CharField(blank=True, choices=[('RESEARCH_FACULTY', 'Research-based (Faculty)'), ('RESEARCH_STUDENT', 'Research-based (Student)'), ('REQUEST_BASED', 'Request-based'), ('OTHER', 'Other')], default='', max_length=40)),
                ('scope_type', models.CharField(blank=True, choices=[('PROGRAM', 'Program (1 year / 3 days min)'), ('PROJECT', 'Project (collection of programs)'), ('ACTIVITY', 'Activity only')], default='', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('implementing_agency', models.CharField(blank=True, default='', max_length=255)),
                ('budgetary_requirement', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('beneficiaries_who', models.TextField(blank=True, default='')),
                ('extension_site', models.CharField(blank=True, default='', max_length=255)),
                ('date_venue', models.TextField(blank=True, default='')),
                ('rationale', models.TextField(blank=True, default='')),
                ('significance', models.TextField(blank=True, default='')),
                ('objectives_general', models.TextField(blank=True, default='')),
                ('objectives_specific', models.TextField(blank=True, default='')),
                ('methodology', models.TextField(blank=True, default='')),
                ('output_outcome', models.TextField(blank=True, default='')),
                ('gender_issues', models.JSONField(blank=True, default=list)),
                ('monitoring_eval', models.TextField(blank=True, default='')),
                ('is_locked', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('beneficiaries_count', models.PositiveIntegerField(blank=True, null=True)),
                ('participants_total', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantsProfiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_male', models.PositiveIntegerField(blank=True, null=True)),
                ('sex_female', models.PositiveIntegerField(blank=True, null=True)),
                ('gender_lesbian', models.PositiveIntegerField(blank=True, null=True)),
                ('gender_gay', models.PositiveIntegerField(blank=True, null=True)),
                ('gender_bisexual', models.PositiveIntegerField(blank=True, null=True)),
                ('gender_transgender', models.PositiveIntegerField(blank=True, null=True)),
                ('gender_straight_male', models.PositiveIntegerField(blank=True, null=True)),
                ('gender_straight_female', models.PositiveIntegerField(blank=True, null=True)),
                ('gender_others', models.PositiveIntegerField(blank=True, null=True)),
                ('gender_others_specify', models.CharField(blank=True, default='', max_length=120)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiling', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DETAILS_ACTIVITIES', 'Details of Activities (Work Plan/Gantt/etc.)'), ('MONITORING_EVAL', 'Monitoring & Evaluation (Reports)'), ('ABSTRACT', 'Research Abstract'), ('CERT_COMPLETION', 'Certificate of Completion'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('file', models.FileField(upload_to='proposal_uploads/%Y/%m/')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField()),
                ('metric', models.CharField(max_length=50)),
                ('value', models.PositiveIntegerField(default=0)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalProponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, default='', max_length=200)),
                ('specialization', models.CharField(blank=True, default='', max_length=200)),
                ('role', models.CharField(blank=True, default='', max_length=120)),
                ('cp_number', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proponents', to='proposals.proposal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='proposals.proposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('proposal', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ProposalThrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thrusts', to='proposals.proposal')),
                ('thrust', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proposals.extensionthrust')),
            ],
            options={
                'unique_together': {('proposal', 'thrust')},
            },
        ),
        migrations.CreateModel(
            name='ProposalSDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdgs', to='proposals.proposal')),
                ('sdg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proposals.sdg')),
            ],
            options={
                'unique_together': {('proposal', 'sdg')},
            },
        ),
    ]
