# Generated by Django 6.0.2 on 2026-03-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='research_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
