# Generated by Django 6.0.2 on 2026-03-04 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_proposal_research_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_projects', to='proposals.proposal')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
