# Generated by Django 6.0.2 on 2026-03-05 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0004_programproject_leader_user"),
    ]

    operations = [
        # ✅ Add new columns (nullable so existing rows won't break)
        migrations.AddField(
            model_name="proposalsdg",
            name="sdg_code",
            field=models.CharField(max_length=10, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="proposalthrust",
            name="thrust_name",
            field=models.CharField(max_length=255, null=True, blank=True),
        ),

        # ✅ related_name changes are state-only; DB doesn't care, but safe to keep
        migrations.AlterField(
            model_name="proposalsdg",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sdg_links",
                to="proposals.proposal",
            ),
        ),
        migrations.AlterField(
            model_name="proposalthrust",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thrust_links",
                to="proposals.proposal",
            ),
        ),
    ]