# Generated by Django 6.0.2 on 2026-03-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_alter_proposalsdg_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposalsdg',
            unique_together={('proposal', 'sdg_code')},
        ),
        migrations.AlterUniqueTogether(
            name='proposalthrust',
            unique_together={('proposal', 'thrust_name')},
        ),
        migrations.AlterField(
            model_name='proposalsdg',
            name='sdg_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.RemoveField(
            model_name='proposalsdg',
            name='sdg',
        ),
        migrations.RemoveField(
            model_name='proposalthrust',
            name='thrust',
        ),
    ]
