# Generated by Django 6.0.2 on 2026-03-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_alter_proposalsdg_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsdg',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposalthrust',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
