# Generated by Django 6.0.2 on 2026-03-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_proposalsdg_explanation_proposalthrust_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='budgetary_requirement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
