# Generated by Django 6.0.2 on 2026-03-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_alter_proposal_budgetary_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='g_bisexual',
            field=models.BigIntegerField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='g_gay',
            field=models.BigIntegerField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='g_lesbian',
            field=models.BigIntegerField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='g_others',
            field=models.BigIntegerField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='g_straight',
            field=models.BigIntegerField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='g_transgender',
            field=models.BigIntegerField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='sex_female',
            field=models.BigIntegerField(blank=True, default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='sex_male',
            field=models.BigIntegerField(blank=True, default=0, max_length=100),
        ),
    ]
