# Generated by Django 6.0.2 on 2026-03-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_proposal_g_bisexual_proposal_g_gay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='completed_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposal',
            name='skipped_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='g_bisexual',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='g_gay',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='g_lesbian',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='g_others',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='g_straight',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='g_transgender',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='sex_female',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='sex_male',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
