# Generated by Django 6.0.2 on 2026-03-11 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_proposal_completed_steps_proposal_skipped_steps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalGenderIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key', models.CharField(max_length=100)),
                ('issue_label', models.TextField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_issue_links', to='proposals.proposal')),
            ],
        ),
    ]
