# Generated by Django 6.0.2 on 2026-03-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_proposaleditorpresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaleditorpresence',
            name='step',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
