# Generated by Django 6.0.2 on 2026-03-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_proposaleditorpresence_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='extension_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='extension_venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
