# Generated by Django 6.0.2 on 2026-03-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0014_proposal_extension_date_proposal_extension_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='extension_date',
        ),
        migrations.AddField(
            model_name='proposal',
            name='estimated_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='estimated_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
