# Generated by Django 6.0.2 on 2026-03-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0015_remove_proposal_extension_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='rationale_background',
            field=models.TextField(blank=True, null=True),
        ),
    ]
