# Generated by Django 6.0.2 on 2026-03-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0016_proposal_rationale_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='significance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
