# Generated by Django 6.0.2 on 2026-03-12 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0017_alter_proposal_significance'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='general_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProposalSpecificObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.TextField()),
                ('program_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_objectives', to='proposals.programproject')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specific_objectives', to='proposals.proposal')),
            ],
        ),
    ]
