# Generated by Django 6.0.2 on 2026-03-12 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0019_proposalmethodology'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalOutputOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_outcomes', to='proposals.proposal')),
            ],
        ),
    ]
