# Generated by Django 6.0.2 on 2026-03-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0020_proposaloutputoutcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalattachment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='proposalattachment',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='proposalattachment',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='proposal',
            name='category',
            field=models.CharField(default='details_of_activities', max_length=50),
        ),
        migrations.AddField(
            model_name='proposal',
            name='gantt_chart_file',
            field=models.FileField(blank=True, null=True, upload_to='proposal_files/gantt_charts/'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='work_plan_file',
            field=models.FileField(blank=True, null=True, upload_to='proposal_files/work_plans/'),
        ),
        migrations.AddField(
            model_name='proposalattachment',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposalattachment',
            name='file',
            field=models.FileField(upload_to='proposal_files/attachments/'),
        ),
    ]
