# Generated by Django 6.0.2 on 2026-03-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0021_remove_proposalattachment_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='category',
        ),
        migrations.AddField(
            model_name='proposalattachment',
            name='category',
            field=models.CharField(default='details_of_activities', max_length=50),
        ),
    ]
