# Generated by Django 6.0.2 on 2026-03-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0022_remove_proposal_category_proposalattachment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='extension_type',
            field=models.CharField(blank=True, choices=[('RESEARCH_FACULTY', 'Research-based (Faculty)'), ('RESEARCH_STUDENT', 'Research-based (Student)'), ('REQUEST_BASED', 'Request-based'), ('OTHER', 'Community-based')], default='', max_length=40),
        ),
    ]
