# Generated by Django 6.0.2 on 2026-03-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0023_alter_proposal_extension_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalgenderissue',
            name='other_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
