# Generated by Django 6.0.2 on 2026-03-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0024_proposalgenderissue_other_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='budgetary_requirement',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='general_objective',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='rationale_background',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='scope_type',
            field=models.CharField(blank=True, choices=[('PROGRAM', 'Program (collection of projects)'), ('PROJECT', 'Project'), ('ACTIVITY', 'Activity only')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='significance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='proposalattachment',
            name='category',
            field=models.CharField(choices=[('details_of_activities', 'Details of Activities'), ('monitoring_eval', 'Monitoring and Evaluation'), ('abstract', 'Research Abstract'), ('cert_completion', 'Certificate of Completion'), ('other', 'Other')], default='details_of_activities', max_length=50),
        ),
    ]
