# Generated by Django 6.0.2 on 2026-03-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0025_proposalattachment_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='certificate_of_completion_file',
            field=models.FileField(blank=True, null=True, upload_to='proposal_files/certificates_of_completion/'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='funding_file',
            field=models.FileField(blank=True, null=True, upload_to='proposal_files/funding/'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='monitoring_file',
            field=models.FileField(blank=True, null=True, upload_to='proposal_files/monitoring/'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='research_abstract_file',
            field=models.FileField(blank=True, null=True, upload_to='proposal_files/research_abstracts/'),
        ),
    ]
