# Generated by Django 6.0.2 on 2026-03-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0026_proposal_certificate_of_completion_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='monitoring_file',
        ),
    ]
