# Generated by Django 6.0.2 on 2026-03-19 00:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0027_remove_proposal_monitoring_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-last_saved_at']},
        ),
        migrations.AlterField(
            model_name='proposal',
            name='extension_type',
            field=models.CharField(blank=True, choices=[('RESEARCH_FACULTY', 'Research-based (Faculty)'), ('RESEARCH_STUDENT', 'Research-based (Student)'), ('REQUEST_BASED', 'Request-based'), ('COMMUNITY_BASED', 'Community-based')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('UNDER_EVALUATION', 'Under Evaluation'), ('FOR_REVISION', 'Returned for Revision'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('FOR_SIGNATURES', 'For Signatures'), ('FINAL_DOCUMENTS_UPLOADED', 'Final Documents Uploaded'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='proposalproponent',
            unique_together={('proposal', 'user')},
        ),
        migrations.CreateModel(
            name='ProposalReviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('department_review_done', models.BooleanField(default=False)),
                ('campus_review_done', models.BooleanField(default=False)),
                ('director_review_done', models.BooleanField(default=False)),
                ('evaluator_review_required', models.BooleanField(default=False)),
                ('evaluator_review_done', models.BooleanField(default=False)),
                ('ready_for_staff_summary', models.BooleanField(default=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_rounds', to='proposals.proposal')),
            ],
            options={
                'ordering': ['round_no'],
                'unique_together': {('proposal', 'round_no')},
            },
        ),
        migrations.CreateModel(
            name='ProposalFinalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('SIGNED_PROPOSAL', 'Signed Proposal'), ('EXTENSION_AGREEMENT', 'Extension Agreement'), ('ENDORSEMENT_FOR_APPROVAL', 'Endorsement for Approval'), ('LETTER_OF_AWARD', 'Letter of Award')], max_length=50)),
                ('file', models.FileField(upload_to='proposal_final_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_documents', to='proposals.proposal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('proposal', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='ProposalEvaluatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_evaluators', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_evaluator_assignments', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_assignments', to='proposals.proposal')),
                ('review_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_assignments', to='proposals.proposalreviewround')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('proposal', 'review_round', 'evaluator')},
            },
        ),
        migrations.CreateModel(
            name='ProposalCommentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('sent_to_proponent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_summaries', to='proposals.proposal')),
                ('review_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='proposals.proposalreviewround')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('proposal', 'review_round')},
            },
        ),
        migrations.CreateModel(
            name='ProposalSectionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_role', models.CharField(choices=[('DEPARTMENT_COORDINATOR', 'Department Coordinator'), ('CAMPUS_COORDINATOR', 'Campus Coordinator'), ('DIRECTOR', 'Director'), ('EVALUATOR', 'Evaluator')], max_length=50)),
                ('step_no', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(19)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('is_visible_to_proponent', models.BooleanField(default=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_comments', to='proposals.proposal')),
                ('review_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='proposals.proposalreviewround')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['step_no', 'created_at'],
                'unique_together': {('proposal', 'review_round', 'reviewer', 'step_no')},
            },
        ),
    ]
