# Generated by Django 6.0.2 on 2026-03-19 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0028_alter_proposal_options_alter_proposal_extension_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposalcollaborator',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='proposalcommentsummary',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='proposaleditorpresence',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='proposalevaluatorassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='proposalfinaldocument',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='proposalproponent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='proposalreviewround',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='proposalsdg',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='proposalsectioncomment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='proposalthrust',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='g_bisexual',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='g_gay',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='g_lesbian',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='g_others',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='g_straight',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='g_transgender',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='sex_female',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='sex_male',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddConstraint(
            model_name='proposalcollaborator',
            constraint=models.UniqueConstraint(fields=('proposal', 'user'), name='unique_proposal_collaborator'),
        ),
        migrations.AddConstraint(
            model_name='proposalcommentsummary',
            constraint=models.UniqueConstraint(fields=('proposal', 'review_round'), name='unique_comment_summary_per_round'),
        ),
        migrations.AddConstraint(
            model_name='proposaleditorpresence',
            constraint=models.UniqueConstraint(fields=('proposal', 'user'), name='unique_proposal_editor_presence'),
        ),
        migrations.AddConstraint(
            model_name='proposalevaluatorassignment',
            constraint=models.UniqueConstraint(fields=('proposal', 'review_round', 'evaluator'), name='unique_evaluator_assignment_per_round'),
        ),
        migrations.AddConstraint(
            model_name='proposalfinaldocument',
            constraint=models.UniqueConstraint(fields=('proposal', 'document_type'), name='unique_final_document_type_per_proposal'),
        ),
        migrations.AddConstraint(
            model_name='proposalproponent',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('proposal', 'user'), name='unique_proposal_proponent_user_nonnull'),
        ),
        migrations.AddConstraint(
            model_name='proposalreviewround',
            constraint=models.UniqueConstraint(fields=('proposal', 'round_no'), name='unique_proposal_review_round'),
        ),
        migrations.AddConstraint(
            model_name='proposalsdg',
            constraint=models.UniqueConstraint(fields=('proposal', 'sdg_code'), name='unique_proposal_sdg'),
        ),
        migrations.AddConstraint(
            model_name='proposalsectioncomment',
            constraint=models.UniqueConstraint(fields=('proposal', 'review_round', 'reviewer', 'step_no'), name='unique_section_comment_per_reviewer_step_round'),
        ),
        migrations.AddConstraint(
            model_name='proposalthrust',
            constraint=models.UniqueConstraint(fields=('proposal', 'thrust_name'), name='unique_proposal_thrust'),
        ),
    ]
