# Generated by Django 6.0.2 on 2026-03-19 09:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0029_alter_proposalcollaborator_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='endorsement_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='extension_agreement_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='final_reports_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='implementation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='implementation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='letter_of_award_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='partial_reports_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='review_level',
            field=models.CharField(blank=True, choices=[('DEPARTMENT', 'Department'), ('CAMPUS', 'Campus'), ('DIRECTOR', 'Director')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='estimated_month',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='extension_venue',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposalattachment',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposalcollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalcommentsummary',
            name='prepared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_comment_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposaleditorpresence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_editor_presences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalfinaldocument',
            name='document_type',
            field=models.CharField(choices=[('SIGNED_PROPOSAL', 'Signed Proposal'), ('EXTENSION_AGREEMENT', 'Extension Agreement'), ('ENDORSEMENT_FOR_APPROVAL', 'Endorsement for Approval'), ('LETTER_OF_AWARD', 'Letter of Award'), ('MOA', 'Memorandum of Agreement'), ('REPORT_PARTIAL', 'Partial Report'), ('REPORT_FINAL', 'Final Report'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proposalfinaldocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_proposal_final_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalgenderissue',
            name='other_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='proposalproponent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_proponentships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalsdg',
            name='sdg_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proposalsectioncomment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_section_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalsectioncomment',
            name='step_no',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
