# Generated by Django 6.0.2 on 2026-03-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0030_proposal_closed_at_proposal_endorsement_released_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='highest_implementation_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='highest_moa_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='highest_proposal_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='implementation_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PREPARATION', 'Preparation'), ('MONITORING', 'Monitoring'), ('POST_ACTIVITY_REPORT', 'Post Activity Report / Progress Report'), ('TERMINAL_REPORT', 'Terminal Report'), ('TERMINAL_REVIEW', 'Review of Terminal Report'), ('REVISION', 'Revision'), ('COMPLETED', 'Implementation Completed')], default='NOT_STARTED', max_length=30),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('NOT_STARTED', 'Not Started'), ('DRAFT', 'Draft'), ('LEGAL_REVIEW', 'Legal Review'), ('FOR_REVISION', 'Under Revision'), ('CERTIFICATION_READY', 'Certification Ready'), ('AGENDA_AND_PRESENTATION', 'Agenda Brief & Presentation'), ('COMPLETED', 'MOA Completed')], default='NOT_STARTED', max_length=30),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_status',
            field=models.CharField(choices=[('DRAFTING', 'Drafting'), ('SUBMITTED_FOR_REVIEW', 'Submitted for Review'), ('IN_REVIEW', 'In Review'), ('REVIEW_SUMMARY_ISSUED', 'Review Summary Issued'), ('FOR_REVISION', 'For Revision'), ('READY_FOR_PRINTING', 'Ready to Print'), ('FOR_SUBMISSION_AND_UPLOAD', 'Submission & Uploading of the Proposal'), ('APPROVED', 'Approved / Claiming'), ('COMPLETED', 'Proposal Completed')], default='DRAFTING', max_length=40),
        ),
        migrations.AddField(
            model_name='proposal',
            name='requires_moa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'In Progress'), ('COMPLETED', 'Extension Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
