# Generated by Django 6.0.2 on 2026-04-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0031_proposal_highest_implementation_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalreviewround',
            name='summary_file',
            field=models.FileField(blank=True, null=True, upload_to='summaries/'),
        ),
        migrations.AddField(
            model_name='proposalreviewround',
            name='summary_generated',
            field=models.BooleanField(default=False),
        ),
    ]
