# Generated by Django 6.0.2 on 2026-04-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0032_proposalreviewround_summary_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalreviewround',
            name='summary_file',
        ),
        migrations.RemoveField(
            model_name='proposalreviewround',
            name='summary_generated',
        ),
    ]
