# Generated by Django 6.0.2 on 2026-04-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0033_remove_proposalreviewround_summary_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='scope_type',
            field=models.CharField(blank=True, choices=[('PROGRAM', 'Program'), ('PROJECT', 'Project'), ('ACTIVITY', 'Activity only')], default='', max_length=20),
        ),
    ]
