# Generated by Django 6.0.2 on 2026-05-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0034_alter_proposal_scope_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='approved_docx_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
