# Generated by Django 6.0.2 on 2026-05-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0035_proposal_approved_docx_downloaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='approved_docx_downloaded_at',
        ),
    ]
