# Generated by Django 6.0.2 on 2026-07-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0037_proposalphaselog_and_implementation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='moa_draft_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]