# Generated by Django 6.0.2 on 2026-07-08 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0038_proposal_moa_draft_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalfinaldocument',
            options={'ordering': ['-version', '-uploaded_at']},
        ),
        migrations.RemoveConstraint(
            model_name='proposalfinaldocument',
            name='unique_final_document_type_per_proposal',
        ),
        migrations.AddField(
            model_name='proposalfinaldocument',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proposalfinaldocument',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='proposalfinaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('proposal', 'document_type'), name='unique_current_final_document_per_type'),
        ),
    ]