# Generated by Django 6.0.6 on 2026-07-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0039_proposalfinaldocument_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='moa_background',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_confidentiality',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_deliverables',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_draft_file',
            field=models.FileField(blank=True, null=True, upload_to='proposal_files/moa_drafts/'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_obligations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_party_one_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_party_one_representative',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_party_two_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_party_two_representative',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_reference_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_signatories_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='moa_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
