# Generated by Django 6.0.6 on 2026-07-17 00:21

import django.db.models.deletion
import proposals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0040_proposal_moa_background_proposal_moa_confidentiality_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MOASubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_agency_name', models.CharField(max_length=255, verbose_name='Name of Partner Agency')),
                ('partner_address', models.TextField(verbose_name='Address of Partner Agency')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year')),
                ('duration', models.PositiveSmallIntegerField(default=3, verbose_name='Duration (years)')),
                ('moa_file', models.FileField(upload_to=proposals.models.moa_upload_path, verbose_name='MOA Draft File')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moa_submission', to='proposals.proposal')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moa_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MOA Submission',
            },
        ),
    ]
