# Generated by Django 5.2.17 on 2026-09-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0044_proposal_is_legacy_proposal_legacy_proposal_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalproponent',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='proposalproponent',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposalproponent',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
