# Generated by Django 5.2.17 on 2026-09-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0046_proponent_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='duration',
            field=models.CharField(blank=True, default='', help_text="Training Design: activity duration (e.g. 'October 23, 2025' or '3 days').", max_length=255),
        ),
        migrations.AddField(
            model_name='proposal',
            name='funding_source',
            field=models.CharField(blank=True, default='', help_text="Training Design: funding source (e.g. 'CTE Extension Fund').", max_length=255),
        ),
        migrations.AddField(
            model_name='proposal',
            name='monitoring_eval_file',
            field=models.FileField(blank=True, help_text='Extension Proposal: Monitoring and Evaluation Mechanics attachment.', null=True, upload_to='proposal_files/monitoring_evaluation/'),
        ),
    ]
