# Generated by Django 5.2.17 on 2026-09-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0047_proposal_duration_proposal_funding_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='technology_title',
            field=models.CharField(blank=True, default='', help_text='Extension Proposal: title of the technology generated.', max_length=300),
        ),
        migrations.AddField(
            model_name='proposal',
            name='utility_model_description',
            field=models.TextField(blank=True, default='', help_text='Extension Proposal: description of the utility model.'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='utility_model_registration_number',
            field=models.CharField(blank=True, default='', help_text='Extension Proposal: utility model registration number.', max_length=120),
        ),
    ]
