# Generated by Django 5.2.17 on 2026-09-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0049_undo_flow_split_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='technology_title',
            field=models.CharField(blank=True, default='', help_text='Utility Model step: title of the technology (N/A if not applicable).', max_length=300),
        ),
        migrations.AddField(
            model_name='proposal',
            name='utility_model_description',
            field=models.TextField(blank=True, default='', help_text='Utility Model step: description of the utility model (N/A if not applicable).'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='utility_model_registration_number',
            field=models.CharField(blank=True, default='', help_text='Utility Model step: utility model registration number (N/A if not applicable).', max_length=120),
        ),
    ]
