# Generated by Django 5.2.17 on 2026-09-23 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0055_proposal_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTemplateOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('form1_program_template.docx', 'Form 1 — Extension Program Proposal'), ('form1_project_template.docx', 'Form 1 — Extension Project Proposal'), ('form2_training_design_template.docx', 'Form 2 — Training Design'), ('clear_summary_template.docx', 'Clearance Summary'), ('program_work_plan_template.xlsx', 'Program Work Plan'), ('project_work_plan_template.xlsx', 'Project Work Plan'), ('program_gantt_chart_template.xlsx', 'Program Gantt Chart'), ('project_gantt_chart_template.xlsx', 'Project Gantt Chart'), ('program_funding_template.xlsx', 'Program Line-Item Budget'), ('project_funding_template.xlsx', 'Project Line-Item Budget')], help_text='Which built-in template this file replaces.', max_length=80, unique=True)),
                ('file', models.FileField(upload_to='proposal_templates/')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional note, e.g. what changed in this revision.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposal template',
                'verbose_name_plural': 'Proposal templates',
                'ordering': ['key'],
            },
        ),
    ]
