# Generated by Django 5.2.17 on 2026-09-23 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0056_proposal_template_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProposalTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('key', models.CharField(help_text='Stable identifier for this file, e.g. moa-renewal-form.docx.', max_length=120, unique=True)),
                ('file', models.FileField(upload_to='proposal_templates/custom/')),
                ('notes', models.TextField(blank=True, default='', help_text='What this file is for, or what changed in this revision.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive files stay stored but are marked as not in use.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom proposal template',
                'verbose_name_plural': 'Custom proposal templates',
                'ordering': ['title'],
            },
        ),
    ]
