# Generated by Django 6.0.2 on 2026-02-21 14:35
import django_ckeditor_5.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('vision', 'Vision'), ('mission', 'Mission'), ('process', 'Process'), ('targets', 'Targets')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(config_name="default")),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(upload_to='personnel/')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='details.extensionprocess')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2025)),
                ('campus', models.CharField(max_length=100)),
                ('metric', models.CharField(choices=[('programs', 'Programs'), ('participants', 'Participants'), ('partners', 'Partners'), ('technology', 'Technology Transfer')], max_length=32)),
                ('planned_q1', models.PositiveIntegerField(default=0)),
                ('planned_q2', models.PositiveIntegerField(default=0)),
                ('planned_q3', models.PositiveIntegerField(default=0)),
                ('planned_q4', models.PositiveIntegerField(default=0)),
                ('planned_total', models.PositiveIntegerField(default=0)),
                ('actual_q1', models.PositiveIntegerField(default=0)),
                ('actual_q2', models.PositiveIntegerField(default=0)),
                ('actual_q3', models.PositiveIntegerField(default=0)),
                ('actual_q4', models.PositiveIntegerField(default=0)),
                ('actual_total', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['campus', 'metric'],
                'unique_together': {('year', 'campus', 'metric')},
            },
        ),
    ]
