# Generated by Django 6.0.2 on 2026-02-22 01:22

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('vision', 'Vision'), ('mission', 'Mission')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
