# Generated by Django 6.0.2 on 2026-02-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_alter_page_content_alter_page_page_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
