# Generated by Django 6.0.2 on 2026-03-02 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_remove_activity_date_alter_activity_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extensionprocess',
            options={},
        ),
        migrations.AlterModelOptions(
            name='processstep',
            options={},
        ),
        migrations.AlterField(
            model_name='extensionprocess',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='process',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='details.extensionprocess'),
            preserve_default=False,
        ),
    ]
