# Generated by Django 5.2.17 on 2026-08-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0013_alter_accomplishmentreport_id_alter_activity_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformfield',
            name='depends_on_key',
            field=models.CharField(blank=True, default='', help_text='The key of the parent field this field depends on.', max_length=120),
        ),
        migrations.AddField(
            model_name='dynamicformfield',
            name='depends_on_value',
            field=models.CharField(blank=True, default='', help_text='The parent field value(s), comma-separated, that make this field visible.', max_length=255),
        ),
    ]
