# Generated by Django 5.2.17 on 2026-09-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0014_dynamicformfield_depends_on_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homethrust',
            name='color_class',
            field=models.CharField(choices=[('text-yellow-600', 'Gold'), ('text-blue-600', 'Blue'), ('text-yellow-500', 'Yellow'), ('text-purple-600', 'Purple'), ('text-red-600', 'Red'), ('text-indigo-600', 'Indigo'), ('text-pink-500', 'Pink'), ('text-teal-600', 'Teal'), ('text-orange-500', 'Orange'), ('text-yellow-700', 'Deep Gold'), ('text-rose-500', 'Rose'), ('text-amber-500', 'Amber'), ('text-cyan-600', 'Cyan'), ('text-violet-600', 'Violet'), ('text-gray-700', 'Gray')], default='text-yellow-600', help_text='Accent colour for the card title.', max_length=40),
        ),
    ]
