# Generated by Django 5.2.17 on 2026-09-18 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0016_workflow_phase_weight_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicformfield',
            name='maps_to',
            field=models.CharField(blank=True, choices=[('full_name', 'Name'), ('designation', 'Position / Designation'), ('specialization', 'Specialization'), ('role', 'Role'), ('cp_number', 'CP Number'), ('email', 'Email')], default='', help_text='For repeatable groups that store proponents: which proponent record column this field fills in. Blank fields are kept as extra details of that proponent.', max_length=40),
        ),
        migrations.AddField(
            model_name='dynamicformtemplate',
            name='is_repeater',
            field=models.BooleanField(default=False, help_text='Repeatable group: the fields below are shown once per row and the proponent can add as many rows as they need.'),
        ),
        migrations.AddField(
            model_name='dynamicformtemplate',
            name='repeater_label',
            field=models.CharField(blank=True, default='', help_text='Name of one row, e.g. "Proponent". Used in buttons and messages.', max_length=80),
        ),
        migrations.AddField(
            model_name='dynamicformtemplate',
            name='repeater_max_rows',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximum number of rows. 0 = no limit.'),
        ),
        migrations.AddField(
            model_name='dynamicformtemplate',
            name='repeater_min_rows',
            field=models.PositiveSmallIntegerField(default=0, help_text='Rows the proponent must fill in before the step can be completed.'),
        ),
        migrations.AddField(
            model_name='dynamicformtemplate',
            name='row_store',
            field=models.CharField(choices=[('GENERIC', 'Saved with this form (free-standing rows)'), ('PROPONENT', 'Proponents of the proposal (Step 3)')], default='GENERIC', help_text="Only used for repeatable groups: store each row as a free-standing row, or as one of the proposal's proponents.", max_length=20),
        ),
        migrations.CreateModel(
            name='DynamicFormRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='details.dynamicformresponse')),
            ],
            options={
                'ordering': ['row_index', 'id'],
            },
        ),
    ]
