# Generated by Django 5.2.17 on 2026-09-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0018_seed_proponent_repeater_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOAWizardStepConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveSmallIntegerField(unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Position in the wizard. 0 falls back to the step number.')),
                ('section_key', models.CharField(blank=True, default='', help_text='Built-in part rendered on this step. Blank = office-built forms only.', max_length=60)),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('instructions', models.TextField(blank=True, default='')),
                ('is_visible', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'step_no'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='proposalwizardstepconfig',
            options={'ordering': ['order', 'step_no']},
        ),
        migrations.AddField(
            model_name='dynamicformtemplate',
            name='attached_proposal_steps',
            field=models.ManyToManyField(blank=True, help_text='Proposal wizard steps this form is shown on. Follows the step when the office reorders the wizard, and one form can serve several steps.', related_name='attached_forms', to='details.proposalwizardstepconfig'),
        ),
        migrations.AddField(
            model_name='proposalwizardstepconfig',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Position in the wizard. 0 falls back to the step number.'),
        ),
        migrations.AddField(
            model_name='proposalwizardstepconfig',
            name='section_key',
            field=models.CharField(blank=True, default='', help_text='Built-in part rendered on this step. Blank = office-built forms only.', max_length=60),
        ),
        migrations.AddField(
            model_name='dynamicformtemplate',
            name='attached_moa_steps',
            field=models.ManyToManyField(blank=True, help_text='MOA drafting steps this form is shown on.', related_name='attached_forms', to='details.moawizardstepconfig'),
        ),
    ]
