# Generated by Django 5.2.17 on 2026-09-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0021_undo_wizard_step_parts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalwizardstepconfig',
            options={'ordering': ['flow', 'step_no']},
        ),
        migrations.AddField(
            model_name='dynamicformtemplate',
            name='wizard_flow',
            field=models.CharField(blank=True, choices=[('ALL', 'All proposal types'), ('RESEARCH', 'Research-based (Extension Proposal)'), ('TRAINING', 'Community/Request-based (Training Design)')], default='', help_text='For forms attached to a proposal wizard step: which wizard flow this form belongs to. Blank means the form is shared by every flow that has this step number (for example the shared Step 1 and the proponent repeater on Step 3).', max_length=20),
        ),
        migrations.AddField(
            model_name='proposalwizardstepconfig',
            name='flow',
            field=models.CharField(choices=[('ALL', 'All proposal types'), ('RESEARCH', 'Research-based (Extension Proposal)'), ('TRAINING', 'Community/Request-based (Training Design)')], default='ALL', help_text="Which proposal type's wizard shows this step.", max_length=20),
        ),
        migrations.AlterField(
            model_name='proposalwizardstepconfig',
            name='step_no',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='proposalwizardstepconfig',
            constraint=models.UniqueConstraint(fields=('flow', 'step_no'), name='unique_wizard_step_per_flow'),
        ),
    ]
