# Generated by Django 5.2.17 on 2026-09-21 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0031_wizard_step_display_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='cta_label',
            field=models.CharField(blank=True, default='', help_text='Call-to-action block only: button text, e.g. “Start a proposal”.', max_length=120),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='cta_url',
            field=models.CharField(blank=True, default='', help_text='Call-to-action block only: destination — a site path like /register/ or a full URL starting with https://.', max_length=300),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='limit_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Activities / Personnel blocks only: how many items to show. Leave blank to show all.', null=True),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='target_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Targets block only: which year to display. Leave blank to use the latest year with data.', null=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='layout',
            field=models.CharField(choices=[('RICH_TEXT', 'Rich text'), ('CARD', 'Card'), ('CALLOUT', 'Callout / highlight'), ('CTA', 'Call to action'), ('ACTIVITIES', 'Extension activities'), ('TARGETS', 'Targets (planned vs. actual)'), ('PROCESSES', 'Extension processes'), ('TEMPLATES', 'Template library'), ('PERSONNEL', 'Extension personnel')], default='RICH_TEXT', max_length=20),
        ),
        migrations.CreateModel(
            name='PageContentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPDATE_PAGE', 'Updated page'), ('ADD_SECTION', 'Added section'), ('EDIT_SECTION', 'Edited section'), ('DELETE_SECTION', 'Deleted section'), ('MOVE_SECTION', 'Moved section')], max_length=20)),
                ('page_slug', models.SlugField(max_length=40)),
                ('section_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, default='', help_text='Human label of what changed, e.g. the section heading.', max_length=220)),
                ('summary', models.CharField(max_length=255)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_content_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page Content Log',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
