# Generated by Django 5.2.17 on 2026-09-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0037_wizard_template_download_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processstep',
            options={'ordering': ('order', 'id')},
        ),
    ]
