# Generated by Django 5.2.17 on 2026-10-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0042_annual_target_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
