# Generated by Django 5.2.18 on 2026-10-09 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0043_alter_target_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave empty for a top-level step, or pick the step this one sits under.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='details.processstep'),
        ),
    ]
